### ISSUE TITLE
Possible change to Financial Transactions

### ISSUE THREAD

**Issue by Cobchise** [umts/golf-cart-rentals#400]
Currently financial transactions have no destroy method. It was left this way because Metin wanted a paper trail and didn't want payments to be 'deletable' however we implemented the [permanent records gem](https://github.com/JackDanger/permanent_records) a long time ago which overrides destroy methods. This gem adds a deleted_at column to models meaning when destroy is called, models are not removed but instead become 'deactivated'.

We may want to implement a destroy method for financial transactions in the future.

**Comment by nawilliams** [comment]
Permanent records has been removed and we're just using paper trail now.
