### ISSUE TITLE
View tests (low priority)

### ISSUE THREAD

**Issue by tomecho** [umts/golf-cart-rentals#57]
There are none

**Comment by dfaulken** [comment]
Depending how JS-reliant your views are, I might suggest integration tests either rather than, or in addition to, view testing.

**Comment by tomecho** [comment]
I spent a lot of time using selenium this summer.  I don't see much of a necessity right now but eventually, it would be nice to add some integration tests.

**Comment by anmerkl** [comment]
Going to work on integration tests - keeping this unassigned so other people can feel motivated to open the issue and work on it also...

**Comment by anmerkl** [comment]
Integration tests proving to be a little to difficult/cumbersome at the moment.
Progress contained in "integration-tests" branch for anybody that wants to pick this up in the future.

**Comment by Anbranin** [comment]
I can definitely pass this off to someone else for a little while, I know you've been banging your head against a wall for a bit.

**Comment by nawilliams** [comment]
closing because we're doing integration tests instead of view tests
